### ISSUE TITLE
Add/Edit Polyline/Polygon features

### ISSUE THREAD

**Issue by shujaatak** [moovida/smash#96] opened 2021-01-30 12:57 UTC
After reading the relevant instructions here: https://www.geopaparazzi.org/smash/index.html#_feature_editing
I downloaded [natural_earth_vector](http://naciscdn.org/naturalearth/packages/natural_earth_vector.gpkg.zip) from https://www.naturalearthdata.com/downloads/, unzipped to a folder in my Samsung Note-5 having Android Version 7. I started SMASH Application, opened **Layer List** page, clicked on **Load Local Datasets**, browsed to the folder where I had placed **natural_earth_vector.qpkg**, clicked on it to open it, SMASH shows a list of tables to select from, I select **ne_10m_admin_0_boundary_lines_land**. I then enable the features editing tool. Although I **long tap** on features in the map to select the feature below but nothing happens.

I don't know whether this a bug or I am missing something or doing something entirely wrong. 

An editable sample vector map and clear instructions would be much appreciated.

**Comment by shujaatak** [comment] 2021-01-31 06:09
I am trying to load a sample geopackage multipolygon map made in QGIS but SMASH shows **Loading...** message forever and does not load the map.

**Comment by shujaatak** [comment] 2021-01-31 07:12
@moovida When I create a geopackage with polygon rather than a multipolygon then SMASH successfully load it and show the polygon on the map but still it does not allow me to edit or add new features in the layer no matter how long I tap on the screen.

I might be missing something or there is a bug in the app.

**Comment by shujaatak** [comment] 2021-01-31 07:18
The **query features from loaded vector layers** tool works perfectly. It lets me see and edit the fields as expected but **Modify geometries in editable vector layers** tool does not work.

I simply create a geopackage layer in QGIS add some polygons and then load in my **Samsung Note-5** SMASH app. I don't know if there is something more to do with geopackage before loading in SMASH.

**Comment by shujaatak** [comment] 2021-02-01 06:23
I think my geopackage layer is fine as if I do not load geopackage layer then when I **long tap** on the map, I get warning **"No editable layer is currently loaded.**". This means there might be a bug in the app.

**Comment by moovida** [comment] 2021-02-01 06:39
Good morning @shujaatak , you have been busy :-) But here we were on weekend. Now I am here.

Can you send me the geopackage database to see what is wrong?

**Comment by shujaatak** [comment] 2021-02-01 06:41
Good Morning @moovida , Going to send you the geopackage in a moment.

**Comment by shujaatak** [comment] 2021-02-01 06:50
I have zipped the geopackage file and the screenshot of the location where I have drawn the polygon. The location is random near the New York.
[SamplePolygon.zip](https://github.com/moovida/smash/files/5902306/SamplePolygon.zip)

**Comment by shujaatak** [comment] 2021-02-01 06:59
@moovida Using **query features from loaded vector layers** tool, I can edit sample polygon name to **National Recreation Area** from **Nation Recreation Area**. This means this tool works fine but the other one not.

**Comment by shujaatak** [comment] 2021-02-01 07:10
No matter which type I select, SMASH does not allow me to edit.

These are the geometries which I have tried using QGIS.
![Geometries](https://user-images.githubusercontent.com/14161646/106425738-2a1ef800-6486-11eb-85bc-b082313d8efc.png)

**Comment by moovida** [comment] 2021-02-01 07:15
Ok, I found it and it is a bug (which is now fixed). I have no idea how this regression slipped into the release.
Right now the only way to solve this is to set the vector layer settings:

![image](https://user-images.githubusercontent.com/390250/106426235-8d4c6280-6465-11eb-8974-0229498c83ad.png)

to load all features:

![image](https://user-images.githubusercontent.com/390250/106426264-99382480-6465-11eb-80d6-c2fa73c9e9d4.png)

Then it should work.
Could try and confirm me that?

**Comment by shujaatak** [comment] 2021-02-01 07:19
Exactly same settings I have by default. I also different values but no effect.

**Comment by moovida** [comment] 2021-02-01 07:23
So you are telling me that:

* you set max number to **all**
* reload the geopackage layer
* do not see this:
![image](https://user-images.githubusercontent.com/390250/106426899-b15c7380-6466-11eb-823f-5d40f1aeb5b3.png)

What happens?

**Comment by shujaatak** [comment] 2021-02-01 07:31
- I set max number to **all**
- I delete/remove geopackage layer by swiping left and tapping on delete (as **Max number of features** settings require removing and adding layer back to apply the settings) 
- I re-add the geopackage then I see this:

![](https://user-images.githubusercontent.com/390250/106426899-b15c7380-6466-11eb-823f-5d40f1aeb5b3.png)

- I then enable **Modify geometries and editable layers** tool to try to modify the polygon by **long tapping** on it but nothing happens.

**Comment by moovida** [comment] 2021-02-01 07:32
Ah, ok, sorry, before it would not even load it, so I was stuck there. Let me check the editing now. Thanks.

**Comment by moovida** [comment] 2021-02-01 07:49
Ok, found the issue. In fact the addition of postgis brought in a regression that wasn't yet present in the testcases :-(
Fixing it.

**Comment by moovida** [comment] 2021-02-01 08:04
Ok, this is fixed now:
![image](https://user-images.githubusercontent.com/390250/106430625-5cbbf700-646c-11eb-9efc-d9e5e6d17ff7.png)

![image](https://user-images.githubusercontent.com/390250/106430647-65143200-646c-11eb-89cb-a6a141c2af7a.png)

I will try to do a release asap, but I have limited time. Do you need a package to test on right now?

**Comment by shujaatak** [comment] 2021-02-01 08:05
It would be helpful if I get the package.

**Comment by moovida** [comment] 2021-02-01 08:07
Do you need an android package? It would maybe even be better if you could test it before releasing it. It might be that you find other issues that I would then want to fix.
If it is android, I can make a build and upload it for testing.

**Comment by shujaatak** [comment] 2021-02-01 08:09
Yes, it is android.

I would be more than happy to test the app and post issues if I find.

**Comment by moovida** [comment] 2021-02-01 08:18
Here you go @shujaatak : https://we.tl/t-uzGPIGa3MQ
Contains an apk for all android architectures. Let me know how it works.

**Comment by shujaatak** [comment] 2021-02-01 08:30
On **Project View** screen when I click on **Open an existing project** or **Create a new project**, SMASH crashes.

**Comment by shujaatak** [comment] 2021-02-01 08:30
I have uninstalled the SMASH app which I had downloaded from the Play Store.

**Comment by moovida** [comment] 2021-02-01 08:31
Testing now

**Comment by moovida** [comment] 2021-02-01 08:31
Do you get any error message?

**Comment by shujaatak** [comment] 2021-02-01 08:33
I see this message from android:
**SMASH has stopped.** Restart app.

**Comment by shujaatak** [comment] 2021-02-01 08:35
To put this in your knowledge, I allow all those permissions which SMASH ask for.

**Comment by moovida** [comment] 2021-02-01 08:36
Tried to do the same. Uninstalled and ran. 
I am not able to reproduce the issue. Can you look if you see something in the diagnostic debug log from the settings?

**Comment by shujaatak** [comment] 2021-02-01 08:41
It's my 5th time I am reinstalling the **smash_1.6.4RC1.apk** but getting the same issue. Before installation I also deleted any old SMAH folders etc.

I can't access settings as SMASH crashes after the **Project View** screen.

**Comment by moovida** [comment] 2021-02-01 08:42
ahhh, the one at startup, not even when you navigate to it. Ok, let me try to also remove the folder and test it.

**Comment by shujaatak** [comment] 2021-02-01 08:44
Ah, finally I am able to create new project, **the issue was that I had my GPS turned off**.

**Comment by moovida** [comment] 2021-02-01 08:46
Ok, need to try that one then. You are a very good tester :-D Thank you.

**Comment by moovida** [comment] 2021-02-01 08:53
@shujaatak I am not able to reproduce this. I tried removing the smash folder, and switching off the GPS. But everything works as expected. Does something else come to your mind?

**Comment by shujaatak** [comment] 2021-02-01 08:53
Another issue.
SMAH help is fantastic **but** it doesn't work correctly the first time when it automatically starts after SMASH installation. The SMASH help covers the whole screen with blue color and one can't interact with the app. I had to simply close the app and re-run it. 

Upon restarting SMASH the help works correctly. One can interact with the app to move to next help step.

**Comment by shujaatak** [comment] 2021-02-01 08:55
I have yet another issue.

SMASH continuously crashes after running for a while. **I think** it crashes as soon as it tries to access GPS.

**Comment by shujaatak** [comment] 2021-02-01 08:56
> @shujaatak I am not able to reproduce this. I tried removing the smash folder, and switching off the GPS. But everything works as expected. Does something else come to your mind?

On my side, if I turn off GPS then SMASH can't get to **main screen**. It simply crashes.

**Comment by moovida** [comment] 2021-02-01 08:58
You turn off the gps but then give permission to use it, right?

**Comment by shujaatak** [comment] 2021-02-01 08:58
After turning on GPS, Smash allow me to create/open projects otherwise it simply crashes when I try to create/open a project.

**Comment by shujaatak** [comment] 2021-02-01 09:00
> You turn off the gps but then give permission to use it, right?

When I run SMASH for the first time, it asks for some permissions. I allow all those permissions including permission for accessing GPS.

**Comment by moovida** [comment] 2021-02-01 09:01
Accessing GPS all the time or only while using app?
And then after that you turn off the GPS and it crashes when restarting the app?

**Comment by shujaatak** [comment] 2021-02-01 09:14
Scenario 1:

- I have GPS turned off. Tap on SMASH icon to run it. In the startup, SMASH shows **Project View** page. Now SMASH crashes **as soon as** I tap on either **Open an existing project** or **Create a new project**.

Scenario 2:

- When I turn on GPS before running SMASH.  Tap on SMASH icon to run it.  In the startup, SMASH shows **Project View** page. Now when I tap on either **Open an existing project** or **Create a new project**, SMASH **doesn't crash**. I can successfully create a new project and get into the main screen. **BUT** while in the main screen, SMASH crashes after a few seconds. It looks to me that after some interval SMASH tries to access GPS and somehow it crashes there.

**Comment by moovida** [comment] 2021-02-01 09:16
Hi @shujaatak I am desperately trying to make the app crash, but am not able to. Something happens when you do it.
I think I need every step from the installation process to what you describe above. I am sorry, but have no idea how to fix this else.

**Comment by shujaatak** [comment] 2021-02-01 09:18
Do you know of some android screen recording app? If so, I can install it and record a video.

**Comment by shujaatak** [comment] 2021-02-01 09:21
Found app. Going to record video.

**Comment by moovida** [comment] 2021-02-01 09:22
Thanks man!

**Comment by shujaatak** [comment] 2021-02-01 09:46
Here it is https://we.tl/t-odiemeLXSu

**Comment by moovida** [comment] 2021-02-01 10:00
Ok, I am watching the very good video, thanks.
I have some ideas about the problems:

1. When I am asked for permissions, I can set the *use location also in background* and I always do that. Can you try to do that also in some location setting your android version should have? I just noticed that there is a n issue if I select only use while app in use (which is what your should use by default).
2. for me the location is orange also with gps switched off. I am wondering if it is taking it from some other network setting. Looking at that also.

Also, I do not remember if you told me, what android version are you on?

**Comment by shujaatak** [comment] 2021-02-01 10:07
I have SAMSUNG-NOTE-5, Android Version 7.0.

I have given all possible permissions, In my android I have no option to set the _use location also in background_. 

I re-installed SMASH from Play Store and I notice that it doesn't crash any single time. The only problem it has is that it does not allow me to edit geometries.

**Comment by moovida** [comment] 2021-02-01 10:09
That is odd. Few changed from the last version, I will have to see if some dependency has updated automatically declaring compatibility but instead screwed things up... this is really a pain

**Comment by shujaatak** [comment] 2021-02-01 10:16
SMASH is fantastic app and I am hopeful that issues will be resolved as soon as they are discovered.  I am always here to test it on my android phone and report back issues if I find any.

**Comment by moovida** [comment] 2021-02-01 10:26
Thanks a lot @shujaatak , I really want to fix this. Not having an android 7 phone at hand makes this difficult.

Could you try this version here: https://we.tl/t-6ViHaY4cES
I tried to revert the gps library to the one used in version 1.6.3 that is on the store.

**Comment by shujaatak** [comment] 2021-02-01 10:48
Still same behavior.

**Comment by shujaatak** [comment] 2021-02-01 10:50
@moovida Going to try it on another phone but surely Android version would still be not latest.

**Comment by shujaatak** [comment] 2021-02-01 11:08
OK, I tried on another phone having Android Version 9. SMASH crash if I have GPS Off, same as another phone. When GPS is on, I noticed that SMASH runs fine and it gets GPS lock quickly too. **But I accidentally noticed that SMASH crashed as soon as I turned off GPS.**
It clearly shows that GPS code has some issue.

**Comment by moovida** [comment] 2021-02-01 11:09
Thanks a ton @shujaatak , I will now put my effort in trying to reproduce this, since it is my only way to fix it. I will keep you posted.

**Comment by shujaatak** [comment] 2021-02-01 11:19
Just to let you know, I tried editing/creating polygons. I am so happy that it really worked great without any issues.

**Comment by shujaatak** [comment] 2021-02-01 11:30
I have found three more issues but I will not bombard issues here. I will post them as soon as the issue in hand is resolved i.e. when the SMASH stops crashing.

**Comment by moovida** [comment] 2021-02-01 11:32
Please @shujaatak , feel free to open a new issue for each of it, so that we can keep track and discuss them one by one :-) Thank you.

**Comment by shujaatak** [comment] 2021-02-01 11:45
In my phone, SMASH continuously crashes so I cant work on it. As I had borrowed someone phone for a while and now returned it so I can't test SMASH anymore.

The three issues I faced are:

1. If a geopackage database has no feature in it then SMASH can't load it. SMASH just shows **Loading...** message forever.
2. In editing mode, I can't discard changes.
3. In editing mode, I can't delete a feature. 

In editing mode, I was able to save changes only!

**Comment by shujaatak** [comment] 2021-02-01 13:02
@moovida Looking at your following screenshot I noticed that in my case the whole polygon(both fill color and lines) was drawn in pure black opaque color, not like the one show below:
![image](https://user-images.githubusercontent.com/14161646/106461525-b47f5000-64b6-11eb-8d46-acb6ef127267.png)

**Comment by moovida** [comment] 2021-02-01 13:04
Yep, you can set the color from the layers list. Just swipe the layer tile to the right and select properties.

**Comment by shujaatak** [comment] 2021-02-01 13:08
Can you please push latest changes to GitHub so that I may try to debug it on my side?

**Comment by moovida** [comment] 2021-02-01 13:12
@shujaatak this is a great great news. I just pushed everything. If you need help to locate the places, I would be more than happy to direct you. We can use any kind of chat from telegram to gitter or mailinglist.

**Comment by shujaatak** [comment] 2021-02-01 13:12
Oh Sorry just checked that you already have updated the repository.

**Comment by moovida** [comment] 2021-02-01 14:49
@shujaatak are you still online? I might have found something. But I will create a package only if you can test it :-) I am not sure if you are in a compatible timezone.

**Comment by shujaatak** [comment] 2021-02-01 14:51
Yes I am here to test it!

> @shujaatak are you still online? I might have found something. But I will create a package only if you can test it :-) I am not sure if you are in a compatible timezone.

Yes I am here to test it.

**Comment by moovida** [comment] 2021-02-01 14:52
Ahh, great. You want me to push and test the code directly?

**Comment by shujaatak** [comment] 2021-02-01 14:53
For now, package is more suitable as I would be able to test it quickly.

**Comment by moovida** [comment] 2021-02-01 14:58
here it is: https://we.tl/t-zFmTGCCZLk

**Comment by shujaatak** [comment] 2021-02-01 15:02
Unfortunately it has same behavior.

**Comment by moovida** [comment] 2021-02-01 15:06
Also when the gps is on? Does it still crash? Did you uninstall and redo from scratch?

**Comment by moovida** [comment] 2021-02-01 15:08
In the meanwhile good news: I have been able to reproduce the start crash when the gps is off on an old phone!!! :-)

**Comment by shujaatak** [comment] 2021-02-01 15:10
Here good new too! Now SMASH doesn't crash when GPS is ON but as soon as I turn off GPS SMASH crashes.

**Comment by shujaatak** [comment] 2021-02-01 15:12
Your latest edits solves half of the issue!

**Comment by moovida** [comment] 2021-02-01 15:12
Fantastic, then that all makes sense:
- my fix should have solved the gps issue.
- and now I have to fix the on GPS off issue. I never noticed it because I had the WIFI scan service on

If I am lucky, this should be fixed by the day :-)

**Comment by moovida** [comment] 2021-02-01 16:16
This is not as simple to implement as I thought. Anyways I made a fix and checked most possible cases. It doesn't crash also when I disable it during fix. I made some tests now and here is one for you to test: https://we.tl/t-ETgjruF9me

**Comment by shujaatak** [comment] 2021-02-01 16:33
Tested the latest package and I noticed that SMASH crashes.

Steps to reproduce:
- Keep GPS off
- Start SMASH
- Open Project
- Now turn on GPS, as soon as I turn on GPS, SMASH smashes!

**Comment by shujaatak** [comment] 2021-02-01 16:51
> In my phone, SMASH continuously crashes so I cant work on it. As I had borrowed someone phone for a while and now returned it so I can't test SMASH anymore.
> 
> The three issues I faced are:
> 
> 1. If a geopackage database has no feature in it then SMASH can't load it. SMASH just shows **Loading...** message forever.
> 2. In editing mode, I can't discard changes.
> 3. In editing mode, I can't delete a feature.
> 
> In editing mode, I was able to save changes only!

I am so sorry that issue number 2 and 3 are not issues. It was my fault that I was not long tapping action buttons used for discarding changes and deleting features.

**Comment by moovida** [comment] 2021-02-01 17:12
I am afraid the crash when the GPS is turned on doesn't happen to me. I follow the steps. With gps off i enter a project and once I see the red gps icon, I turn on the gps. The icon gets orange to show no fix available and then eventually green. No crash here. Do you have anything in the log?

**Comment by shujaatak** [comment] 2021-02-01 17:28
App crashes after **Geolocator initialized** log.

Log:
```
22:25:06.268
Geolocator initialized.
22:25:06.250
Register for location updates.
22:25:06.231
Initialize geolocator.
```

**Comment by shujaatak** [comment] 2021-02-01 17:32
When GPS is off, I see **red GPS icon with cross**. When I turn on GPS, the icon changes to yellow circle then after sometime the app crashes.

**Comment by shujaatak** [comment] 2021-02-01 17:49
Using **smash_1.6.4RC1_test3** SMASH was not crashing when I was turning on GPS but it was crashing when I was turning off GPS.

Now in **smash_1.6.4RC1_test4** the response is inverse! SMASH crashes when I turn on GPS but it is not crashing when I keep GPS off.

**Comment by moovida** [comment] 2021-02-01 18:02
So to reproduce your issue I should:
* start with gps off
* when I see the map and the red gps icon
* turn gps on and wait
Right?

**Comment by shujaatak** [comment] 2021-02-01 18:03
Yes!

**Comment by shujaatak** [comment] 2021-02-01 18:07
I reinstalled **smash_1.6.4RC1_test3** and I noticed that It also crashes when I turn on GPS. I don't know why but **smash_1.6.4RC1_test3** had worked with GPS once correctly.

**Comment by moovida** [comment] 2021-02-01 18:08
:-( I have no idea why this doesn't happen to me. I also tried to reinstall.

So you say that it crashes also when you start with gps on as soon as the points come in?

**Comment by shujaatak** [comment] 2021-02-01 18:11
Yes that's also true!

**Comment by shujaatak** [comment] 2021-02-01 18:13
SMASH version 1.6.3 downloaded from Play Store works perfectly in all situations but it has issues with geometries editing only.

**Comment by moovida** [comment] 2021-02-01 18:14
Yes, maybe I should start from there...

**Comment by moovida** [comment] 2021-02-01 18:16
I will now revert the code to that version and ask you to check if the package works.

**Comment by shujaatak** [comment] 2021-02-01 18:16
Android Version 7 and below has more than 10% Market Share Worldwide otherwise we may have included them in non-supported list.

**Comment by shujaatak** [comment] 2021-02-01 18:17
> I will now revert the code to that version and ask you to check if the package works.

I am ready to test!

**Comment by moovida** [comment] 2021-02-01 18:23
Ok, version is here. Built from 1.6.3 tag. Let's see if we can start from that: https://we.tl/t-YWH0kYdJCu

**Comment by shujaatak** [comment] 2021-02-01 18:30
Tested it and it works perfectly! Behaves same as the one downloaded from Play Store.

Let me tell you one thing about the SMASH available on Play Store, It doesn't switch green icon to red GPS icon when I turn off GPS but otherwise perfect!

**Comment by moovida** [comment] 2021-02-01 18:33
Yes, that is expected, The current gps lib doesn't have the feature to know when the gps is off. I added a different lib in the last tests to understand what was going on.

Ok, I will try to carefully add back bits and pieces. Let's see if I am able to.

**Comment by moovida** [comment] 2021-02-01 19:03
Ok, here a test with cherry picked gps fixes: https://we.tl/t-johdktPO2Z
It seems that it has to be a GPS library issue though. Everything else seems to work the same.

**Comment by shujaatak** [comment] 2021-02-01 19:14
Wonderful! Congratulations! This version works perfectly! No GPS issues and no geometry editing issues!

**Comment by moovida** [comment] 2021-02-01 19:16
Finally!!!! Then it is indeed a regression in the GPS library! 
I do not think i would have ever been able to solve it without you. Thanks a lot. I will do some more tests tomorrow or so and then i will prepare for a new release.

**Comment by shujaatak** [comment] 2021-02-01 19:18
@moovida You are great! May you stay happy and healthy!

**Comment by shujaatak** [comment] 2021-02-01 19:23
Should we close this issue? 
Also I want to ask if we can consider it an issue if SMASH can't load geopackage database without any feature in it?

**Comment by shujaatak** [comment] 2021-02-02 05:41
@moovida Good Morning! Looking forward to the new SMASH version.

**Comment by moovida** [comment] 2021-02-02 05:51
Good morning! @shujaatak 

regarding to this: "Also I want to ask if we can consider it an issue if SMASH can't load geopackage database without any feature in it?"

You mean a database that has layers but no features in it? It should load it, since it should be possible to add features to it. Do you have a sample? What problem is there?

**Comment by shujaatak** [comment] 2021-02-02 06:00
Yes, I mean a database that has layers but no features in it. 
Going to send you a sample in a moment.

**Comment by moovida** [comment] 2021-02-02 06:02
Great, can you also send one without layers? I will then att those two as a testcase to the geopackage library to make sure they work.

**Comment by shujaatak** [comment] 2021-02-02 06:11
Here is the geopackage which has no features (Polygons in it):
[SamplePolygon.zip](https://github.com/moovida/smash/files/5909057/SamplePolygon.zip)

**Comment by shujaatak** [comment] 2021-02-02 06:19
I created this geopackage with one additional field **name** along with **fid** using QGIS but didn't add any polygons in it. When I load it in SMASH, the SMASH just shows **Loading...** message but do not load it.

**Comment by moovida** [comment] 2021-02-02 06:21
Yep, that is a bug. I will fix it.

**Comment by moovida** [comment] 2021-02-02 06:58
Alright, this is now fixed and works. You can add an empty layer and then add features to it.

I will now close this issue. In case we can reopen it or open a new one to discuss.

**Closed by moovida** 2021-02-02 06:58 UTC
